version: '3.8'

services:
  backend:
    container_name: backend_sample_nest
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - '3000:3000'
    depends_on:
      - db

  frontend:
    container_name: frontend_sample_nest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
    ports:
      - '4000:3000'

  db:
    container_name: mysql_sample_nest
    image: mysql:8.0
    ports:
      - '3006:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=sample_nest
      - MYSQL_DATABASE=sample_nest
      - MYSQL_USER=sample_nest
      - MYSQL_PASSWORD=sample_nest
      - TZ=Asia/Tokyo
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
